---
name: Alien-Selenium
version: 0.06
author:
  - |-
    Mattia Barbon <mbarbon@cpan.org>
    Dominique Quatravaux <domq@cpan.org>
abstract: installing and finding the Selenium Web test framework
license: perl
requires:
  File::Copy: 0
build_requires:
  Archive::Zip: 1
  Test::Builder: 0
  Test::More: 0
provides:
  Alien::Selenium:
    file: lib/Alien/Selenium.pm
    version: 0.06
generated_by: Module::Build version 0.26
no_index:
  directory:
    - examples
    - inc
    - t
