--- #YAML:1.0
name: Alien-Selenium
version: 0.02
author:
  - Mattia Barbon <mbarbon@cpan.org>
abstract: installing and finding the Selenium Web test framework
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
