---
name: Alien-Selenium
version: 0.09
author:
  - |-
    Mattia Barbon <mbarbon@cpan.org>
    Dominique Quatravaux <domq@cpan.org>
abstract: installing and finding the Selenium Web test framework
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Copy: 0
build_requires:
  Archive::Zip: 1
  Test::Builder: 0
  Test::More: 0
provides:
  Alien::Selenium:
    file: lib/Alien/Selenium.pm
    version: 0.09
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
